402
404
401
405
410
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
420
VarDecl(Id(x),IntLiteral(1))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x))
CallExpr(Id(foo),[Id(x)])
421
VarDecl(Id(x),IntLiteral(1))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x),IntLiteral(1))
CallExpr(Id(foo),[Id(x)])
VarDecl(Id(x))
422
VarDecl(Id(x),IntLiteral(1))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x),IntLiteral(1))
CallExpr(Id(foo),[Id(x),Id(y)])
VarDecl(Id(x))
VarDecl(Id(a),[1,2])
423
VarDecl(Id(x),IntLiteral(1))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x),IntLiteral(1))
CallExpr(Id(foo),[Id(x),Id(y)])
VarDecl(Id(x))
VarDecl(Id(a),[1,3])
412
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x))
VarDecl(Id(y))
VarDecl(Id(x),[1,2])
413
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
414
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x))
415
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x))
416
VarDecl(Id(x),FloatLiteral(1.2))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x))
417
VarDecl(Id(x),IntLiteral(1))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x))
418
VarDecl(Id(x),IntLiteral(1))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x))
419
VarDecl(Id(x),IntLiteral(1))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
VarDecl(Id(x))
406
VarDecl(Id(x))
VarDecl(Id(y),ArrayLiteral())
407
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
408
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),ArrayLiteral(IntLiteral(2)))))
408
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(ArrayLiteral(IntLiteral(1)),ArrayLiteral(IntLiteral(2)))))
409
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(IntLiteral(1),FloatLiteral(1.2)))
411
VarDecl(Id(x),StringLiteral(string))
VarDecl(Id(y),[1,2],ArrayLiteral(ArrayLiteral(IntLiteral(1),IntLiteral(2))))
400
VarDecl(Id(x))
VarDecl(Id(y),IntLiteral(1))
403
Tests run  25
Errors  []
[(<CheckSuite.CheckSuite testMethod=test_diff_numofparam_expr>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 34, in test_diff_numofparam_expr\n'
  '    self.assertTrue(TestChecker.test(input,expect,402))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_diff_numofparam_expr_use_ast>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 51, in '
  'test_diff_numofparam_expr_use_ast\n'
  '    self.assertTrue(TestChecker.test(input,expect,404))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 123, in test_func_decl\n'
  '    self.assertTrue(TestChecker.test(input,expect,410))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_10>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 283, in test_func_decl_10\n'
  '    self.assertTrue(TestChecker.test(input,expect,420))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_11>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 302, in test_func_decl_11\n'
  '    self.assertTrue(TestChecker.test(input,expect,421))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_12>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 321, in test_func_decl_12\n'
  '    self.assertTrue(TestChecker.test(input,expect,422))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_13>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 340, in test_func_decl_13\n'
  '    self.assertTrue(TestChecker.test(input,expect,423))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_2>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 142, in test_func_decl_2\n'
  '    self.assertTrue(TestChecker.test(input,expect,412))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_3>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 156, in test_func_decl_3\n'
  '    self.assertTrue(TestChecker.test(input,expect,413))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_4>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 172, in test_func_decl_4\n'
  '    self.assertTrue(TestChecker.test(input,expect,414))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_5>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 191, in test_func_decl_5\n'
  '    self.assertTrue(TestChecker.test(input,expect,415))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_6>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 210, in test_func_decl_6\n'
  '    self.assertTrue(TestChecker.test(input,expect,416))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_7>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 228, in test_func_decl_7\n'
  '    self.assertTrue(TestChecker.test(input,expect,417))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_8>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 246, in test_func_decl_8\n'
  '    self.assertTrue(TestChecker.test(input,expect,418))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_func_decl_9>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 264, in test_func_decl_9\n'
  '    self.assertTrue(TestChecker.test(input,expect,419))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_init_1>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 69, in test_init_1\n'
  '    self.assertTrue(TestChecker.test(input,expect,406))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_init_3>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 89, in test_init_3\n'
  '    self.assertTrue(TestChecker.test(input,expect,408))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_init_4>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 99, in test_init_4\n'
  '    self.assertTrue(TestChecker.test(input,expect,408))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_init_5>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 109, in test_init_5\n'
  '    self.assertTrue(TestChecker.test(input,expect,409))\n'
  'AssertionError: False is not true\n'),
 (<CheckSuite.CheckSuite testMethod=test_no_entry_point>,
  'Traceback (most recent call last):\n'
  '  File "./test/CheckSuite.py", line 132, in test_no_entry_point\n'
  '    self.assertTrue(TestChecker.test(input,expect,411))\n'
  'AssertionError: False is not true\n')]
Test output
 FF..FFFFFFFFFFFFFF.FFFF..
======================================================================
FAIL: test_diff_numofparam_expr (CheckSuite.CheckSuite)
More complex program
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 34, in test_diff_numofparam_expr
    self.assertTrue(TestChecker.test(input,expect,402))
AssertionError: False is not true

======================================================================
FAIL: test_diff_numofparam_expr_use_ast (CheckSuite.CheckSuite)
More complex program
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 51, in test_diff_numofparam_expr_use_ast
    self.assertTrue(TestChecker.test(input,expect,404))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 123, in test_func_decl
    self.assertTrue(TestChecker.test(input,expect,410))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_10 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 283, in test_func_decl_10
    self.assertTrue(TestChecker.test(input,expect,420))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_11 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 302, in test_func_decl_11
    self.assertTrue(TestChecker.test(input,expect,421))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_12 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 321, in test_func_decl_12
    self.assertTrue(TestChecker.test(input,expect,422))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_13 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 340, in test_func_decl_13
    self.assertTrue(TestChecker.test(input,expect,423))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_2 (CheckSuite.CheckSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 142, in test_func_decl_2
    self.assertTrue(TestChecker.test(input,expect,412))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_3 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 156, in test_func_decl_3
    self.assertTrue(TestChecker.test(input,expect,413))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_4 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 172, in test_func_decl_4
    self.assertTrue(TestChecker.test(input,expect,414))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_5 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 191, in test_func_decl_5
    self.assertTrue(TestChecker.test(input,expect,415))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_6 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 210, in test_func_decl_6
    self.assertTrue(TestChecker.test(input,expect,416))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_7 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 228, in test_func_decl_7
    self.assertTrue(TestChecker.test(input,expect,417))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_8 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 246, in test_func_decl_8
    self.assertTrue(TestChecker.test(input,expect,418))
AssertionError: False is not true

======================================================================
FAIL: test_func_decl_9 (CheckSuite.CheckSuite)
Var decl in function
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 264, in test_func_decl_9
    self.assertTrue(TestChecker.test(input,expect,419))
AssertionError: False is not true

======================================================================
FAIL: test_init_1 (CheckSuite.CheckSuite)
Simple program: main
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 69, in test_init_1
    self.assertTrue(TestChecker.test(input,expect,406))
AssertionError: False is not true

======================================================================
FAIL: test_init_3 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 89, in test_init_3
    self.assertTrue(TestChecker.test(input,expect,408))
AssertionError: False is not true

======================================================================
FAIL: test_init_4 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 99, in test_init_4
    self.assertTrue(TestChecker.test(input,expect,408))
AssertionError: False is not true

======================================================================
FAIL: test_init_5 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 109, in test_init_5
    self.assertTrue(TestChecker.test(input,expect,409))
AssertionError: False is not true

======================================================================
FAIL: test_no_entry_point (CheckSuite.CheckSuite)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 132, in test_no_entry_point
    self.assertTrue(TestChecker.test(input,expect,411))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 25 tests in 0.458s

FAILED (failures=20)

